### ISSUE TITLE
模块名中含有`!`符号，就会把!号及后面的全部给截掉了

### ISSUE THREAD

**Issue by hussion** [fex-team/fis3-plugin-module#13]
模式设为`amd`模式下，定义一个模块，内容为：`define(['text!list.tpl'], factory);`，分析出的依赖名是`text`，后面全部被截掉了~

**Comment by oxUnd** [comment]
不支持这种使用方式，请按照官网文档提供的**内置语法**来解决你的问题，谢谢！
