### ISSUE TITLE
添加参数支持扩展 extList

### ISSUE THREAD

**Issue by hanai** [fex-team/fis3-plugin-module#5]
我自己写了个parser来编译es6文件，但是不会被fis3-hook-module识别为module。
希望能够添加一个配置项支持自定 extList

``` js
var extList = ['.js', '.coffee', '.jsx'];
```

**Comment by 2betop** [comment]
ok，我晚点开放成配置项

**Comment by 2betop** [comment]
@hanai es6 是啥后缀来着？

**Comment by hanai** [comment]
@2betop ECMAScript 6

**Comment by 2betop** [comment]
额，我问的是文件后缀， 我见别的 es6 格式的 文件也是 .js ，应该不会出现你说的这个问题。除非你用了其他后缀。

**Comment by 2betop** [comment]
Anywhere, 已经让这个配置化了。https://github.com/fex-team/fis3-hook-module

**Comment by hanai** [comment]
呃我用的后缀就是.es6，考虑就是像coffee,jsx一样，.es6的文件会先经过babel处理。
