### ISSUE TITLE
请问对js是否包裹define的原理是什么

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis3-plugin-module#6]
因为有可能要用到第三方的js，编译出来发现没有被加上define，需要做哪些更改

``` js
fis.hook('module', {
    mode: 'commonJs'
});
// components源码目录下的资源被标注为组件
fis.match(/\/components\/(.*)/i, {
    id: '$1',
    isMod: true
});

// 简化components下的js组件的id
fis.match(/\/components\/(.*)\.js/i, {
    id: '$1'
});
```

**Comment by 2betop** [comment]
还差一步，就是设置 `isMod: true`

``` js
fis.match('/dir/**.js', {
  isMod: true
})
```

**Comment by fancyboynet** [comment]
@2betop 有的，我补全下相关配置

**Comment by 2betop** [comment]
@fancyboynet 还有一种case，就是目标 js 已经写了  define，此插件会在原来的 define 中修改 id ,而不是再包装。

**Comment by 2betop** [comment]
我错了，你是用 commonJs 模式，如果目标 js 中已经写了 define 是不会再包装了。

刚说的 case 只会发生在 mode: 'amd' 的条件下。

**Comment by fancyboynet** [comment]
你是指如果js内容中存在**define**关键字就不会再包装了？

**Comment by 2betop** [comment]
只要 define( 这种语句出现了，且不在注释中，就不会再包装了。

**Comment by 2betop** [comment]
如果你是要用 commonJs 作为规范，那么你用 js 怎么会夹杂 amd 规范的代码呢？兼容用 fis-components 里面的组件，全是 commonJs 规范的。

**Comment by fancyboynet** [comment]
明白了，因为有可能要用第三方的js，所以想知道要怎么改造，自己写的肯定会按commonJs的规范来的

**Comment by 2betop** [comment]
第三方裤，统统用 fis-components 上面提供的，如果没有你现用的，pull request 一个配置文件，就转过来了。 https://github.com/fis-components/components

**Comment by fancyboynet** [comment]
谢谢，components思想很赞，看了一遍，没看懂具体要怎么转...
